/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inscription d'un nouvel utilisateur
         * @description Crée un nouveau compte utilisateur avec un solde initial de 1000
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Nom d'utilisateur unique
                         * @example john_doe
                         */
                        username: string;
                        /**
                         * @description Mot de passe (sera hashé)
                         * @example password123
                         */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Compte créé avec succès */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description ID unique de l'utilisateur
                             * @example 1
                             */
                            user_id?: number;
                            /**
                             * @description Nom d'utilisateur
                             * @example john_doe
                             */
                            username?: string;
                        };
                    };
                };
                /** @description Erreur serveur */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Erreur serveur */
                            error?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Connexion utilisateur
         * @description Authentifie un utilisateur et retourne ses informations
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Nom d'utilisateur
                         * @example john_doe
                         */
                        username: string;
                        /**
                         * @description Mot de passe
                         * @example password123
                         */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Connexion réussie */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Solde de l'utilisateur
                             * @example 1000
                             */
                            money?: number;
                            /**
                             * @description Nom d'utilisateur
                             * @example john_doe
                             */
                            username?: string;
                        };
                    };
                };
                /** @description Authentification échouée */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Utilisateur inconnu */
                            error?: string;
                        };
                    };
                };
                /** @description Erreur serveur */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Erreur serveur */
                            error?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/update_money": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mise à jour du solde utilisateur
         * @description Met à jour le solde d'un utilisateur
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Nom d'utilisateur
                         * @example john_doe
                         */
                        username: string;
                        /**
                         * @description Nouveau solde
                         * @example 950
                         */
                        money: number;
                    };
                };
            };
            responses: {
                /** @description Solde mis à jour */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Nouveau solde
                             * @example 950
                             */
                            money?: number;
                        };
                    };
                };
                /** @description Erreur serveur */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Erreur serveur */
                            error?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nb_total": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Nombre total de vélos par station
         * @description Retourne le nombre total de vélos (électriques + normaux)
         *     pour chaque station, basé sur le dernier horodatage disponible.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Liste des stations avec le total de vélos */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TotalVelos"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nb_elec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Nombre de vélos électriques par station
         * @description Retourne le nombre de vélos électriques
         *     pour chaque station (dernier état connu).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Liste des stations avec vélos électriques */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VeloElec"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nb_normal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Nombre de vélos normaux par station
         * @description Retourne le nombre de vélos classiques (non électriques)
         *     pour chaque station (dernier état connu).
         */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description Numéro de station spécifique (optionnel)
                     * @example 1234
                     */
                    num_station?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Liste des stations avec vélos normaux */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VeloNormal"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/info_statique": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Informations statiques des stations
         * @description Retourne toutes les colonnes de la table `info_station` (équivalent `SELECT *`),
         *     dont notamment le nom, l'identifiant, la capacité et les **coordonnées GPS**
         *     (latitude / longitude au format WGS84, comme dans les données JCDecaux).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Liste des informations statiques des stations */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StationInfo"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/moyennes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Moyenne de vélos par station
         * @description Retourne la moyenne de vélos disponibles par station
         *     (moyenne des vélos normaux + moyenne des vélos électriques),
         *     arrondie à 2 décimales.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Liste des stations avec leur moyenne de vélos */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MoyenneVelos"][];
                    };
                };
                /** @description Erreur serveur */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Erreur serveur */
                            error?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stations/{id}/{type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Historique des données d'une station
         * @description Retourne l'historique des données pour une station spécifique.
         *     Type peut être 'normal', 'elec' ou 'total'.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Numéro de la station
                     * @example 1234
                     */
                    id: number;
                    /**
                     * @description Type de vélos (normal, elec, total)
                     * @example total
                     */
                    type: "normal" | "elec" | "total";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Historique des données de la station */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StationHistory"];
                    };
                };
                /** @description Type invalide */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example type inconnu,\n (types valides: 'normal','elec','total') */
                            error?: string;
                        };
                    };
                };
                /** @description Erreur serveur */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Erreur serveur */
                            error?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TotalVelos: {
            /**
             * @description Nom de la station
             * @example République
             */
            nom?: string;
            /**
             * @description Identifiant de la station
             * @example 1234
             */
            num_station?: number;
            /**
             * @description Nombre total de vélos disponibles
             * @example 15
             */
            total_velos?: number;
        };
        VeloElec: {
            /**
             * @description Nom de la station
             * @example Bellecour
             */
            nom?: string;
            /**
             * @description Identifiant de la station
             * @example 5678
             */
            num_station?: number;
            /**
             * @description Nombre de vélos électriques disponibles
             * @example 5
             */
            velo_elec?: number;
        };
        VeloNormal: {
            /**
             * @description Nom de la station
             * @example Part-Dieu
             */
            nom?: string;
            /**
             * @description Identifiant de la station
             * @example 9101
             */
            num_station?: number;
            /**
             * @description Nombre de vélos classiques disponibles
             * @example 10
             */
            velo_normal?: number;
        };
        MoyenneVelos: {
            /**
             * @description Nom de la station
             * @example Part-Dieu
             */
            nom?: string;
            /**
             * @description Identifiant de la station
             * @example 9101
             */
            num_station?: number;
            /**
             * Format: float
             * @description Moyenne du nombre total de vélos (normal + elec), arrondie à 2 décimales
             * @example 12.47
             */
            moyenne_velos?: number;
        };
        /**
         * @description Ligne de la table `info_station` (schéma aligné sur le remplissage depuis
         *     l'API station_information JCDecaux).
         */
        StationInfo: {
            /**
             * @description ID de la station (clé métier)
             * @example 1234
             */
            id_station?: number;
            /**
             * @description Nom de la station
             * @example Bellecour
             */
            nom?: string;
            /**
             * Format: double
             * @description Latitude (WGS84), en degrés décimaux
             * @example 45.7602
             */
            lat?: number;
            /**
             * Format: double
             * @description Longitude (WGS84), en degrés décimaux
             * @example 4.8357
             */
            lon?: number;
            /**
             * @description Capacité d'emplacements (vélos) de la station
             * @example 20
             */
            capacity?: number;
        } & {
            [key: string]: unknown;
        };
        StationHistory: {
            /**
             * @description Nom de la station
             * @example Bellecour
             */
            nom?: string;
            /**
             * @description ID de la station
             * @example 1234
             */
            num_station?: number;
            historique?: {
                /**
                 * Format: date-time
                 * @description Date et heure de la mesure
                 * @example 2024-01-15T10:30:00Z
                 */
                horodatage?: string;
                /**
                 * @description Nombre de vélos normaux (si type=normal)
                 * @example 8
                 */
                velo_normal?: number;
                /**
                 * @description Nombre de vélos électriques (si type=elec)
                 * @example 5
                 */
                velo_elec?: number;
                /**
                 * @description Nombre total de vélos (si type=total)
                 * @example 13
                 */
                velo_total?: number;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
